# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scooter_availability_pb2 as scooter__availability__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scooter_availability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScooterAvailabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailableScooters = channel.unary_unary(
                '/scooteravailability.ScooterAvailabilityService/CheckAvailableScooters',
                request_serializer=scooter__availability__pb2.CheckAvailableScootersRequest.SerializeToString,
                response_deserializer=scooter__availability__pb2.CheckAvailableScootersResponse.FromString,
                _registered_method=True)
        self.UpdateScooterStatus = channel.unary_unary(
                '/scooteravailability.ScooterAvailabilityService/UpdateScooterStatus',
                request_serializer=scooter__availability__pb2.UpdateScooterStatusRequest.SerializeToString,
                response_deserializer=scooter__availability__pb2.UpdateScooterStatusResponse.FromString,
                _registered_method=True)


class ScooterAvailabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckAvailableScooters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScooterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScooterAvailabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailableScooters': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailableScooters,
                    request_deserializer=scooter__availability__pb2.CheckAvailableScootersRequest.FromString,
                    response_serializer=scooter__availability__pb2.CheckAvailableScootersResponse.SerializeToString,
            ),
            'UpdateScooterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScooterStatus,
                    request_deserializer=scooter__availability__pb2.UpdateScooterStatusRequest.FromString,
                    response_serializer=scooter__availability__pb2.UpdateScooterStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scooteravailability.ScooterAvailabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scooteravailability.ScooterAvailabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScooterAvailabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailableScooters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scooteravailability.ScooterAvailabilityService/CheckAvailableScooters',
            scooter__availability__pb2.CheckAvailableScootersRequest.SerializeToString,
            scooter__availability__pb2.CheckAvailableScootersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScooterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scooteravailability.ScooterAvailabilityService/UpdateScooterStatus',
            scooter__availability__pb2.UpdateScooterStatusRequest.SerializeToString,
            scooter__availability__pb2.UpdateScooterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
