# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scooter_availability.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'scooter_availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ascooter_availability.proto\x12\x13scooteravailability\"\xa1\x01\n\x07Scooter\x12\x12\n\nscooter_id\x18\x01 \x01(\t\x12\x32\n\x06status\x18\x02 \x01(\x0e\x32\".scooteravailability.ScooterStatus\x12\x15\n\rbattery_level\x18\x03 \x01(\x05\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x12\n\nupdated_at\x18\x06 \x01(\t\"[\n\x1d\x43heckAvailableScootersRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x15\n\rradius_meters\x18\x03 \x01(\x05\"P\n\x1e\x43heckAvailableScootersResponse\x12.\n\x08scooters\x18\x01 \x03(\x0b\x32\x1c.scooteravailability.Scooter\"\xa0\x01\n\x1aUpdateScooterStatusRequest\x12\x12\n\nscooter_id\x18\x01 \x01(\t\x12\x32\n\x06status\x18\x02 \x01(\x0e\x32\".scooteravailability.ScooterStatus\x12\x15\n\rbattery_level\x18\x03 \x01(\x05\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\"L\n\x1bUpdateScooterStatusResponse\x12-\n\x07scooter\x18\x01 \x01(\x0b\x32\x1c.scooteravailability.Scooter*l\n\rScooterStatus\x12\x1e\n\x1aSCOOTER_STATUS_UNSPECIFIED\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\n\n\x06RENTED\x10\x02\x12\x0c\n\x08\x43HARGING\x10\x03\x12\x12\n\x0eOUT_OF_SERVICE\x10\x04\x32\x9a\x02\n\x1aScooterAvailabilityService\x12\x81\x01\n\x16\x43heckAvailableScooters\x12\x32.scooteravailability.CheckAvailableScootersRequest\x1a\x33.scooteravailability.CheckAvailableScootersResponse\x12x\n\x13UpdateScooterStatus\x12/.scooteravailability.UpdateScooterStatusRequest\x1a\x30.scooteravailability.UpdateScooterStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scooter_availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOOTERSTATUS']._serialized_start=631
  _globals['_SCOOTERSTATUS']._serialized_end=739
  _globals['_SCOOTER']._serialized_start=52
  _globals['_SCOOTER']._serialized_end=213
  _globals['_CHECKAVAILABLESCOOTERSREQUEST']._serialized_start=215
  _globals['_CHECKAVAILABLESCOOTERSREQUEST']._serialized_end=306
  _globals['_CHECKAVAILABLESCOOTERSRESPONSE']._serialized_start=308
  _globals['_CHECKAVAILABLESCOOTERSRESPONSE']._serialized_end=388
  _globals['_UPDATESCOOTERSTATUSREQUEST']._serialized_start=391
  _globals['_UPDATESCOOTERSTATUSREQUEST']._serialized_end=551
  _globals['_UPDATESCOOTERSTATUSRESPONSE']._serialized_start=553
  _globals['_UPDATESCOOTERSTATUSRESPONSE']._serialized_end=629
  _globals['_SCOOTERAVAILABILITYSERVICE']._serialized_start=742
  _globals['_SCOOTERAVAILABILITYSERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
